server:
  port: 8081
spring:
  application:
    name: microservice-a
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-zone: ${SPRING_CLOUD_CONSUL_DISCOVERY_INSTANCE_ZONE}
        hostname: microservice-a
        health-check-path: /actuator/health
        prefer-ip-address: false
        healthCheckInterval: 10s

microservice-b:
  url: "localhost:8082" # needs to change depending on platform