server:
  port: 8081
  error:
    include-exception: true
spring:
  application:
    name: microservice-a
  cloud:
    consul:
      discovery:
        register: true
        instance-id: ${spring.application.name}-${spring.cloud.client.hostname}-${random.value}
        service-name: microservice-a

feign:
  tsf:
    enabled: true

tsf_consul_ip: "localhost"
tsf_consul_port: "8500"
tsf_application_id: ""
tsf_group_id: ""
tsf_zone: ""
tsf_registry_port: 8080

tsf:
  swagger:
    enabled: false
    