services:
  consul:
    image: hashicorp/consul:latest
    container_name: consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: "consul agent -dev -client=0.0.0.0 -log-level=error"

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      JAVA_TOOL_OPTIONS: -Dtsf_consul_ip=consul -Dtsf_consul_port=8500 -Dtsf_application_id=gateway -Dtsf_group_id=group-dc1 -Dtsf_zone=dc1 -Dtsf_registry_port=8080
    depends_on:
      - consul

  microservice-a:
    build: ./microservice-a
    container_name: microservice-a
    ports:
      - "8081:8080"
    environment:
      SERVER_PORT: 8080
      JAVA_TOOL_OPTIONS: -Dtsf_consul_ip=consul -Dtsf_consul_port=8500 -Dtsf_application_id=microservice-a -Dtsf_group_id=group-dc1 -Dtsf_zone=dc1 -Dtsf_registry_port=8080
    depends_on:
      - consul

  microservice-b:
    build: ./microservice-b
    container_name: microservice-b
    ports:
      - "8082:8080"
    environment:
      SERVER_PORT: 8080
      JAVA_TOOL_OPTIONS: -Dtsf_consul_ip=consul -Dtsf_consul_port=8500 -Dtsf_application_id=microservice-b -Dtsf_group_id=group-dc1 -Dtsf_zone=dc1 -Dtsf_registry_port=8080
    depends_on:
      - consul