services:
  consul:
    image: hashicorp/consul:latest
    container_name: consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: "consul agent -dev -client=0.0.0.0 -log-level=error"

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_PORT: 8500
      SPRING_APPLICATION_NAME: gateway
    depends_on:
      - consul

  microservice-a:
    build: ./microservice-a
    container_name: microservice-a
    ports:
      - "8081:8080"
    environment:
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_PORT: 8500
      SPRING_APPLICATION_NAME: microservice-a
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_CONSUL: OFF
    depends_on:
      - consul

  microservice-b:
    build: ./microservice-b
    container_name: microservice-b
    ports:
      - "8082:8080"
    environment:
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_PORT: 8500
      SPRING_APPLICATION_NAME: microservice-b
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_CONSUL: OFF
    depends_on:
      - consul