version: "3.9"

services:
  consul:
    image: hashicorp/consul:latest
    container_name: consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: "consul agent -dev -client=0.0.0.0"

  microservice-a:
    build: ./microservice-a
    container_name: microservice-a
    ports:
      - "8080:8080"
    environment:
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_PORT: 8500
      SPRING_APPLICATION_NAME: microservice-a
    depends_on:
      - consul

  microservice-b:
    build: ./microservice-b
    container_name: microservice-b
    ports:
      - "8081:8081"
    environment:
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_PORT: 8500
      SPRING_APPLICATION_NAME: microservice-b
    depends_on:
      - consul