apiVersion: v1
kind: Service
metadata:
  name: gateway
#  namespace: dc1
spec:
  selector:
    app: gateway
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
#  namespace: dc1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      initContainers:
        - name: wait-for-consul
          image: busybox
          command: ['sh', '-c', 'until nc -z consul.default.svc.cluster.local 8500; do sleep 5; done']
      containers:
        - name: gateway
          image: spring-cloud-gateway-and-consul-multi-zone-gateway:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_CLOUD_CONSUL_HOST
              value: "consul.default.svc.cluster.local"
            - name: SPRING_CLOUD_CONSUL_PORT
              value: "8500"
            - name: SPRING_CLOUD_CONSUL_DISCOVERY_REGISTER
              value: "true"
            - name: SPRING_CLOUD_CONSUL_DISCOVERY_INSTANCE_ZONE
              value: "dc1"
            - name: SERVER_PORT
              value: "8080"