apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-b
spec:
  replicas: 3
  selector:
    matchLabels:
      app: microservice-b
  template:
    metadata:
      labels:
        app: microservice-b
    spec:
      containers:
      - name: microservice-b
        image: spring-cloud-gateway-and-consul-multi-zone-microservice-b:latest
        ports:
        - containerPort: 8081