---
apiVersion: v1
kind: Service
metadata:
  name: microservice-a
  namespace: dc1
spec:
  selector:
    app: microservice-a
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-a
  namespace: dc1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-a
  template:
    metadata:
      labels:
        app: microservice-a
    spec:
      initContainers:
        - name: wait-for-consul
          image: busybox
          command: ['sh', '-c', 'until nc -z consul.default.svc.cluster.local 8500; do sleep 5; done']
      containers:
        - name: microservice-a
          image: spring-cloud-gateway-and-consul-multi-zone-microservice-a:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: JAVA_TOOL_OPTIONS
              value: >-
                -Dtsf_consul_ip=consul.default.svc.cluster.local
                -Dtsf_consul_port=8500
                -Dtsf_application_id=microservice-a
                -Dtsf_group_id=group-dc1
                -Dtsf_zone=dc1
                -Dtsf_registry_port=8080


