server:
  port: 8082
  error:
    include-exception: true
spring:
  application:
    name: microservice-b
feign:
  tsf:
    enabled: true
tsf_consul_port: 8500
tsf_application_id: microservice-b-id
tsf_group_id: group-a
tsf:
  swagger:
    enabled: false
